#pragma once

#define CONFIG_SOBA_MIC_BCLK_GPIO (-1)
#define CONFIG_SOBA_MIC_WS_GPIO (-1)
#define CONFIG_SOBA_MIC_DATA_GPIO (-1)
#define CONFIG_SOBA_SPK_BCLK_GPIO (-1)
#define CONFIG_SOBA_SPK_WS_GPIO (-1)
#define CONFIG_SOBA_SPK_DATA_GPIO (-1)
#define CONFIG_SOBA_MIC_MUTE_GPIO (-1)
#define CONFIG_SOBA_STOP_GPIO (-1)
#define CONFIG_SOBA_START_GPIO (-1)
#define CONFIG_SOBA_END_TURN_GPIO (-1)
#define CONFIG_SOBA_STATUS_LED_GPIO (-1)
#define CONFIG_SOBA_PROVISION_BUTTON_GPIO (-1)
#define CONFIG_SOBA_MIC_ACTIVE_LEVEL 0
#define CONFIG_SOBA_STOP_ACTIVE_LEVEL 0
#define CONFIG_SOBA_START_ACTIVE_LEVEL 0
#define CONFIG_SOBA_END_TURN_ACTIVE_LEVEL 0
#define CONFIG_SOBA_PROVISION_ACTIVE_LEVEL 0
#define CONFIG_SOBA_MIC_SAMPLE_SHIFT 8
#define CONFIG_SOBA_MIC_SAMPLE_BITS 24
